name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: change to dir ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm i -g @microsoft/rush
          rush install
      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          rush build
          npm ci

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 2
#      - name: Git config user
#        uses: snow-actions/git-config-user@v1.0.0
#        with:
#          name: # Service Account's Name
#          email: # Service Account's Email Address
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 16
#      - name: Verify Change Logs
#        run: node common/scripts/install-run-rush.js change --verify
#      - name: Rush Install
#        run: node common/scripts/install-run-rush.js install
#      - name: Rush rebuild
#        run: node common/scripts/install-run-rush.js rebuild --verbose --production
